/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_JniClient */

#ifndef _Included_c_JniClient
#define _Included_c_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_JniClient
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_c_JniClient_getStr
  (JNIEnv *, jobject);

/*
 * Class:     c_JniClient
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_c_JniClient_AddInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
